[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "express",
    "ejs",
    "cookie-parser",
    "multer",
    "multer-storage-cloudinary",
    "cloudinary",
    "pdfkit"
  ]
  included_files = [
    "views/*",
    "views/**/*",
    "public/*",
    "public/**/*",
    "public/images/*",
    "public/images/**/*"
  ]
  directory = "netlify/functions"

[functions.server]
  maxDuration = 30

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "public"

[[redirects]]
  from = "/upload1"
  to = "/.netlify/functions/server/upload1"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[[redirects]]
  from = "/analyze"
  to = "/.netlify/functions/server/analyze"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: *.cloudinary.com; img-src 'self' data: blob: *.cloudinary.com;" 
  