[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "ejs", "multer", "cloudinary", "@google/generative-ai"]
  included_files = [
    "views/**/*",
    "public/**/*"
  ]
[[functions]]
  path = "/download"
  function = "server"
  
[functions.server]
  maxDuration = 30

[[redirects]]
  from = "/"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "/.netlify/functions/server/login"
  status = 200
  force = true

[[redirects]]
  from = "/register"
  to = "/.netlify/functions/server/register"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard"
  to = "/.netlify/functions/server/dashboard"
  status = 200
  force = true

[[redirects]]
  from = "/analyze"
  to = "/.netlify/functions/server/analyze"
  status = 200
  force = true

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS" 
  
